version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test