SQLALCHEMY_DATABASE_URI = 'postgresql://test:test@localhost:5435/test'
SQLALCHEMY_TRACK_MODIFICATIONS = False

REDIS_PASSWORD = "redistest"
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

TOKEN_TIME = 900000
